### ISSUE TITLE
Разбор GameVisualizer

### ISSUE THREAD

**Issue by Kuzuru** [Kuzuru/robots#8]
Необходимо разобраться с классом `GameVisualizer` и понять что в нём происходит. Все данные по процессу необходимо записывать в данный `issue`

**Comment by sladk0ejka** [comment]
GameVisualizer
2 команды, выполняемые с делеем: перерисовка и обновление модели
Слушатель мыши

Timer initTimer
Таймер 

distance
Расчет расстояния между точками

angleTo
Расчет угла 

applyLimits
Лимиты

asNormalizedRadians
Угол в радианы

fillOval
Заполнение овала

drawOval
Обрисовка овала (контур)

setTargetPosition
Координаты таргета

onRedrawEvent
Очередь перерисовки, выполняется после обработки всех ожидающих событий

onModelUpdateEvent
Если расстояние между точками <0.5 return
Если угол от робота к таргету > направления робота?( 0 ) то угловая скорость становится 0.001
else угловая скорость становится  -0.001
moveRobot c определенной скоростью, направлением вращения и временем двигает робота

moveRobot
Много сложных формул
В общем отвечает за движение робота

paint
Отрисовка робота и таргета

drawRobot
AffineTransform - отображение из двумерных координат в другие двумерные координаты, сохраняя "прямолинейность" и "параллельность" линий
Задается цвет

drawTarget
AffineTransform 
Задается цвет
